# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: peer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'peer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npeer.proto\x12\x04peer\"\x19\n\x0b\x45lectionMsg\x12\n\n\x02id\x18\x01 \x01(\x0c\"\x1f\n\x10\x45lectionResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\"*\n\x0eNewPeerAddress\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\",\n\x10UltraPeerAddress\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x32\x85\x01\n\x0bPeerService\x12:\n\x08\x41nnounce\x12\x14.peer.NewPeerAddress\x1a\x16.peer.UltraPeerAddress\"\x00\x12:\n\x0b\x45lectLeader\x12\x11.peer.ElectionMsg\x1a\x16.peer.ElectionResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'peer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELECTIONMSG']._serialized_start=20
  _globals['_ELECTIONMSG']._serialized_end=45
  _globals['_ELECTIONRESPONSE']._serialized_start=47
  _globals['_ELECTIONRESPONSE']._serialized_end=78
  _globals['_NEWPEERADDRESS']._serialized_start=80
  _globals['_NEWPEERADDRESS']._serialized_end=122
  _globals['_ULTRAPEERADDRESS']._serialized_start=124
  _globals['_ULTRAPEERADDRESS']._serialized_end=168
  _globals['_PEERSERVICE']._serialized_start=171
  _globals['_PEERSERVICE']._serialized_end=304
# @@protoc_insertion_point(module_scope)
