# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from Servant.src.transport.grpc_peer import peer_pb2 as Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in Servant/src/transport/grpc_peer/peer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PeerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Announce = channel.unary_unary(
                '/peer.PeerService/Announce',
                request_serializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.PeerAddress.SerializeToString,
                response_deserializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.PeerAddress.FromString,
                _registered_method=True)
        self.ElectLeader = channel.unary_unary(
                '/peer.PeerService/ElectLeader',
                request_serializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.ElectionMsg.SerializeToString,
                response_deserializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Response.FromString,
                _registered_method=True)
        self.ExitNetwork = channel.unary_unary(
                '/peer.PeerService/ExitNetwork',
                request_serializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.PeerAddress.SerializeToString,
                response_deserializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Response.FromString,
                _registered_method=True)
        self.PingBloom = channel.unary_unary(
                '/peer.PeerService/PingBloom',
                request_serializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.BloomFilter.SerializeToString,
                response_deserializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Response.FromString,
                _registered_method=True)
        self.QueryFile = channel.unary_unary(
                '/peer.PeerService/QueryFile',
                request_serializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Query.SerializeToString,
                response_deserializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.QueryResult.FromString,
                _registered_method=True)
        self.QuerySelf = channel.unary_unary(
                '/peer.PeerService/QuerySelf',
                request_serializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Query.SerializeToString,
                response_deserializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.QueryResult.FromString,
                _registered_method=True)
        self.QueryEach = channel.unary_unary(
                '/peer.PeerService/QueryEach',
                request_serializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Query.SerializeToString,
                response_deserializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Files.FromString,
                _registered_method=True)
        self.DownloadFile = channel.unary_stream(
                '/peer.PeerService/DownloadFile',
                request_serializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.FileName.SerializeToString,
                response_deserializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Chunk.FromString,
                _registered_method=True)


class PeerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Announce(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ElectLeader(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExitNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PingBloom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuerySelf(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryEach(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Announce': grpc.unary_unary_rpc_method_handler(
                    servicer.Announce,
                    request_deserializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.PeerAddress.FromString,
                    response_serializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.PeerAddress.SerializeToString,
            ),
            'ElectLeader': grpc.unary_unary_rpc_method_handler(
                    servicer.ElectLeader,
                    request_deserializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.ElectionMsg.FromString,
                    response_serializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Response.SerializeToString,
            ),
            'ExitNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.ExitNetwork,
                    request_deserializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.PeerAddress.FromString,
                    response_serializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Response.SerializeToString,
            ),
            'PingBloom': grpc.unary_unary_rpc_method_handler(
                    servicer.PingBloom,
                    request_deserializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.BloomFilter.FromString,
                    response_serializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Response.SerializeToString,
            ),
            'QueryFile': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryFile,
                    request_deserializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Query.FromString,
                    response_serializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.QueryResult.SerializeToString,
            ),
            'QuerySelf': grpc.unary_unary_rpc_method_handler(
                    servicer.QuerySelf,
                    request_deserializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Query.FromString,
                    response_serializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.QueryResult.SerializeToString,
            ),
            'QueryEach': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryEach,
                    request_deserializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Query.FromString,
                    response_serializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Files.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.FileName.FromString,
                    response_serializer=Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Chunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'peer.PeerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('peer.PeerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PeerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Announce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peer.PeerService/Announce',
            Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.PeerAddress.SerializeToString,
            Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.PeerAddress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ElectLeader(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peer.PeerService/ElectLeader',
            Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.ElectionMsg.SerializeToString,
            Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExitNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peer.PeerService/ExitNetwork',
            Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.PeerAddress.SerializeToString,
            Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PingBloom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peer.PeerService/PingBloom',
            Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.BloomFilter.SerializeToString,
            Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peer.PeerService/QueryFile',
            Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Query.SerializeToString,
            Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.QueryResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuerySelf(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peer.PeerService/QuerySelf',
            Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Query.SerializeToString,
            Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.QueryResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryEach(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/peer.PeerService/QueryEach',
            Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Query.SerializeToString,
            Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Files.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/peer.PeerService/DownloadFile',
            Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.FileName.SerializeToString,
            Servant_dot_src_dot_transport_dot_grpc__peer_dot_peer__pb2.Chunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
