# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from Host_cache_server.grpc_bootstrap import bootstrap_pb2 as bootstrap__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bootstrap_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BootstrapStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestBootstrap = channel.unary_unary(
                '/bootstrap.Bootstrap/RequestBootstrap',
                request_serializer=bootstrap__pb2.JoinRequest.SerializeToString,
                response_deserializer=bootstrap__pb2.JoinResponse.FromString,
                _registered_method=True)
        self.ExitNetwork = channel.unary_unary(
                '/bootstrap.Bootstrap/ExitNetwork',
                request_serializer=bootstrap__pb2.ExitRequest.SerializeToString,
                response_deserializer=bootstrap__pb2.ExitResponse.FromString,
                _registered_method=True)


class BootstrapServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestBootstrap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExitNetwork(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BootstrapServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestBootstrap': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestBootstrap,
                    request_deserializer=bootstrap__pb2.JoinRequest.FromString,
                    response_serializer=bootstrap__pb2.JoinResponse.SerializeToString,
            ),
            'ExitNetwork': grpc.unary_unary_rpc_method_handler(
                    servicer.ExitNetwork,
                    request_deserializer=bootstrap__pb2.ExitRequest.FromString,
                    response_serializer=bootstrap__pb2.ExitResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bootstrap.Bootstrap', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bootstrap.Bootstrap', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Bootstrap(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestBootstrap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bootstrap.Bootstrap/RequestBootstrap',
            bootstrap__pb2.JoinRequest.SerializeToString,
            bootstrap__pb2.JoinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExitNetwork(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bootstrap.Bootstrap/ExitNetwork',
            bootstrap__pb2.ExitRequest.SerializeToString,
            bootstrap__pb2.ExitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
